apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ne3kpr8hw-java-springboot 
  janus-idp.io/tekton: ne3kpr8hw-java-springboot
  backstage.io/kubernetes-id: ne3kpr8hw-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ne3kpr8hw-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml